name: Build Test

on:
  push:
  workflow_dispatch:
  
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install Clang
      run: sudo apt install -y clang-11 llvm-toolchain --install-suggests

    - name: llvm-strip symlink
      run: ln -s /usr/bin/llvm-strip-11 /usr/bin/llvm-strip

    - name: Get dependencies
      run:  go get -v 
      working-directory: "."

    - name: Build
      run: make
      working-directory: "./"

    - uses: actions/upload-artifact@v2
      with:
        name: execsnoop.bin
        path: ./execsnoop.bin

    - name: Upload Linux binary to release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./execsnoop.bin
        asset_name: execsnoop.bin
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
