name: Build Test

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install Clang
      run: sudo apt install -y clang-11 --install-suggests

    - name: Get dependencies
      run:  go get -v 
      working-directory: "."

    - name: Build
      run: make
      working-directory: "./"

    - uses: actions/upload-artifact@v2
      with:
        name: execsnoop.bin
        path: ./execsnoop.bin